### ISSUE TITLE
[Feature] Status bar brightness control

### ISSUE THREAD

**Issue by avidprogrammerc** [halogenOS/android_frameworks_base_archived#10]
I just compiled the source for my OP3T, coming from RR Nougat. I like the approach this team is taking in regards to keeping the codebase nice and clean.

That being said, are there plans to implement this feature in XOS? I may try to add them and open a Gerrit review for it too.

Cheers!

**Comment by msfjarvis** [comment]
Yes we'd like to bring it back sooner than later, you can help make things go along faster by pushing to Gerrit :)

**Comment by xdevs23** [comment]
Go for it, appreciate it.

**Comment by xdevs23** [comment]
This has been open for way too long. If this feature is still supposed to be implemented, please create a PR and we'll take care of getting it onto Gerrit for testing.
